# Generated by Django 2.1.3 on 2018-11-26 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_auto_20181126_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectRatings',
            new_name='SubjectRating',
        ),
    ]
