# Generated by Django 2.1.3 on 2018-11-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectrating',
            old_name='user_id',
            new_name='user',
        ),
    ]
