# Generated by Django 2.1.3 on 2018-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_subjectrating_subject_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
