# Generated by Django 2.1.3 on 2019-01-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20190109_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filled_hours',
            field=models.IntegerField(default=0),
        ),
    ]
